# Generated by Django 5.1.4 on 2024-12-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_profissional_remove_agendamento_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='contato_cliente',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nome_cliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
