# Generated by Django 5.1.3 on 2024-12-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0004_profissional_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
